# Generated by Django 5.1 on 2024-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sandiegocurrentyear_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newyorknearby_trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('guttenberg_nj_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guttenberg_nj_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hoboken_nj_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hoboken_nj_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jersey_city_nj_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jersey_city_nj_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('union_city_nj_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('union_city_nj_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('west_new_york_nj_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('west_new_york_nj_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sandiegonearby_trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('la_mesa_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('la_mesa_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lemon_grove_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lemon_grove_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('national_city_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('national_city_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('santee_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('santee_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spring_valley_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spring_valley_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sanfrancisconearby_trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('belvedere_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('belvedere_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brisbane_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brisbane_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('colma_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daly_city_ca_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daly_city_ca_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewYorkCurrentYear',
        ),
        migrations.DeleteModel(
            name='NewYorkNearbyAreaTrends',
        ),
        migrations.DeleteModel(
            name='NewYorkPrevYear',
        ),
        migrations.DeleteModel(
            name='SanDiegoCurrentYear',
        ),
        migrations.DeleteModel(
            name='SanDiegoNearbyAreaTrends',
        ),
        migrations.DeleteModel(
            name='SanDiegoPrevYear',
        ),
        migrations.DeleteModel(
            name='SanFranciscoCurrentYear',
        ),
        migrations.DeleteModel(
            name='SanFranciscoNearbyAreaTrends',
        ),
        migrations.DeleteModel(
            name='SanFranciscoPrevYear',
        ),
    ]
