# Generated by Django 5.1 on 2024-09-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_surveyquestion_question_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.CharField(max_length=255)),
                ('user_ip', models.GenericIPAddressField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.surveyquestion')),
            ],
        ),
    ]
